### Why Numpy is Faster than List?

* Fixed type
* Faster to read less bytes of memory
* No type checking when iterating through obejects
* Utilizes Contiguous Memory


### Applications of Numpy

* Mathematics
* Plotting
* Backend
* ML







In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype="int16")
print(a)

[1 2 3]


In [3]:
b = np.array([[4,5,6],[7,8,9]])
print(b)

[[4 5 6]
 [7 8 9]]


In [4]:
# Get Dimension
a.ndim


1

In [5]:
# Get Shape
b.shape


(2, 3)

In [6]:
# Get type
a.dtype

dtype('int16')

In [7]:
# Get size
b.itemsize, a.itemsize

(8, 2)

In [8]:
# Get total size
a.nbytes # == a.itemsize * a.size

6

### Accessing/Changing specific elements, rows, columns, etc

In [9]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specific element [r, c]

a[1, 4]

np.int64(12)

In [11]:
# Get a specific row
a[0, :]


array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific col

a[:, 1]

array([2, 9])

In [13]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

# a[0, 1:-1:2]


array([2, 4, 6])

In [14]:
a[1,5] = 20
print(a)

a[:, 2] = 888
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[  1   2 888   4   5   6   7]
 [  8   9 888  11  12  20  14]]


In [15]:
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
# Get a specific element (work outside in)

b[0,1,0]


np.int64(3)

In [19]:
# replace

b[:,1,:] = [[11,22], [55,77]]

In [20]:
b

array([[[ 1,  2],
        [11, 22]],

       [[ 5,  6],
        [55, 77]]])

### Initializing Different Types of Arrays

In [23]:
# All 0s Matrix

np.zeros((2,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
# All 1s Matrix
np.ones((4,2,2), dtype="int32")


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [25]:
# Any other number

np.full((3,3), 22)

array([[22, 22, 22],
       [22, 22, 22],
       [22, 22, 22]])

In [26]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# Random decimal numbers

np.random.rand(4, 2)

array([[0.23659421, 0.53554918],
       [0.95810531, 0.10765432],
       [0.92242797, 0.71238274],
       [0.40708563, 0.56194845]])

In [30]:
np.random.random_sample(b.shape)

array([[[0.26215733, 0.42668785],
        [0.74984422, 0.92839997]],

       [[0.37763358, 0.26521192],
        [0.67793194, 0.46312138]]])

In [33]:
# Radnom integer value
np.random.randint(1,3,size=(3,3))


array([[2, 2, 1],
       [2, 1, 2],
       [2, 2, 1]])

In [37]:
# Identity Matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
# Repeat an array

arr = np.array([[1,2,3]])

r1 = np.repeat(arr, 3, axis=0)

r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [49]:
# Practice


# My Solution
arr = np.ones((5,5))

arr[1,1:4] = 0
arr[2,1:4] = 0
arr[3,1:4] = 0

arr[2,2] = 9

arr




array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be Careful when copying arrays in Numpy

In [53]:
a = np.array([1,2,3])

b = a.copy()

b[0] = 100

a

array([1, 2, 3])

### Mathematics

In [54]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [55]:
a+2

array([3, 4, 5, 6])

In [56]:
a-2

array([-1,  0,  1,  2])

In [57]:
a*2

array([2, 4, 6, 8])

In [58]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [59]:
b = np.array([1,0,1,0])

a+b

array([2, 2, 4, 4])

#### Linear Algebra

In [62]:
a = np.ones((2,3))

print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [63]:
# Find the determinant
c = np.identity(3)

np.linalg.det(c)

np.float64(1.0)

### Statistics

In [64]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.min(stats)

np.int64(1)

In [66]:
np.max(stats)

np.int64(6)

In [67]:
np.min(stats, axis=1)

array([1, 4])

In [68]:
np.sum(stats)

np.int64(21)

### Reorganizing Arrays

In [72]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [74]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
# Horizontal stacking vecotrs

h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

np.hstack([h1,h2])


array([1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous
Load Data from File

In [77]:
 filedata = np.genfromtxt('data.txt', delimiter=',')
 filedata

FileNotFoundError: data.txt not found.