# Assignment 03 - Numpy

Answer the following questions. For each question, use the code cell below to write your solution.

## Question 1

Create a 2D Numpy array with shape (3, 3) containing random integers between 1 and 20.

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1, 21, size=(3,3))
arr

array([[12,  1,  1],
       [13,  2, 12],
       [15,  8, 19]])

## Question 2

Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values for each row.

In [ ]:
arr1 = np.random.rand(5,5)
arr1

array([[0.72473993, 0.4291822 , 0.29232187, 0.95944715, 0.73604761],
       [0.98437182, 0.15215847, 0.32512674, 0.37274087, 0.69472917],
       [0.51336187, 0.92724648, 0.68714972, 0.84940407, 0.10265242],
       [0.30393148, 0.12188664, 0.81454363, 0.54489571, 0.94088306],
       [0.93737871, 0.47992876, 0.43764081, 0.30170865, 0.25396683]])

In [ ]:
arr1.min(axis=1)

array([0.29232187, 0.15215847, 0.10265242, 0.12188664, 0.25396683])

In [ ]:
arr1.max(axis=1)

array([0.95944715, 0.98437182, 0.92724648, 0.94088306, 0.93737871])

## Question 3

Write a NumPy program to create a random vector of size 10 and sort it.

In [ ]:
vector = np.random.random(10)
print(vector)

print("------------------")
sorted_vector = np.sort(vector) # arr.sort() is an on the fly function
print(sorted_vector)
print("------------------")
print(vector)

[0.29058288 0.18574758 0.68298855 0.95459485 0.05675008 0.07257299
 0.70940638 0.52973209 0.17813265 0.16858909]
------------------
[0.05675008 0.07257299 0.16858909 0.17813265 0.18574758 0.29058288
 0.52973209 0.68298855 0.70940638 0.95459485]
------------------
[0.29058288 0.18574758 0.68298855 0.95459485 0.05675008 0.07257299
 0.70940638 0.52973209 0.17813265 0.16858909]


## Question 4

Write a NumPy program to find the most frequent value in an array.

In [ ]:
def most_frequent(arr):
    frequent_nums, counts = np.unique(arr, return_counts=True)
    index_of_highest_count = np.argmax(counts)
    return frequent_nums[index_of_highest_count]



def main():
  my_array = np.array([1, 2, 3, 7, 6, 8, 4, 2, 5, 2, 9, 9, 7, 9, 1, 7, 7])
  most_frequent(my_array)
  print(f"the most frequent value in the array is: {most_frequent(my_array)}")

if __name__ == "__main__":
  main()

the most frequent value in the array is: 7


## Question 5

Replace all even numbers in the 2D array with 0.

In [ ]:
def replace_even_with_zero(arr):
  arr[arr % 2 == 0] = 0
  return arr

def main():
  arr_2D = np.random.randint(1, 21, size=(3,3))
  print(f"Original Array:\n {arr_2D}")
  print("------------------")
  print(f"Array with Zeros:\n {replace_even_with_zero(arr_2D)}")

if __name__ == "__main__":
  main()

Original Array:
 [[ 6  5 19]
 [ 2  2 14]
 [ 5  9  2]]
------------------
Array with Zeros:
 [[ 0  5 19]
 [ 0  0  0]
 [ 5  9  0]]


## Question 6

Apply the square root function to each element of the 1D array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

## Question 7

Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.

In [ ]:
arr1 = np.random.rand(3,3)
arr1

array([[0.61123391, 0.33896521, 0.36740383],
       [0.17188938, 0.45861168, 0.79607632],
       [0.17258647, 0.12101075, 0.17357311]])

In [ ]:
means = arr1.mean(axis=1)
means

array([0.43920098, 0.47552579, 0.15572344])

In [ ]:
arr1[0] -= means[0]
arr1[1] -= means[1]
arr1[2] -= means[2]

arr1

array([[ 0.17203293, -0.10023578, -0.07179715],
       [-0.30363642, -0.01691411,  0.32055053],
       [ 0.01686303, -0.03471269,  0.01784966]])

## Question 8

Create a 1D array containing the first 20 odd numbers.

In [ ]:
arr_1D = np.arange(1, 41, 2)

print(len(arr_1D))

arr_1D


20


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

## Question 9

Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.

In [ ]:
arr = np.random.rand(5,5)
arr

array([[0.81226335, 0.2610471 , 0.21047926, 0.09832372, 0.97905987],
       [0.03192893, 0.08828352, 0.51489971, 0.09087384, 0.54631272],
       [0.82927922, 0.23852551, 0.96020467, 0.08028566, 0.85550318],
       [0.02472375, 0.11564129, 0.35493555, 0.45959366, 0.47490783],
       [0.13831408, 0.41554716, 0.3396748 , 0.50027908, 0.33785994]])

In [ ]:
largest_value_in_col = arr.max(axis=0)
largest_value_in_col

array([0.82927922, 0.41554716, 0.96020467, 0.50027908, 0.97905987])

In [ ]:
index_of_max_value = largest_value_in_col.argmax()
index_of_max_value



np.int64(4)

In [ ]:
largest_value_in_col = np.delete(largest_value_in_col, index_of_max_value)

In [ ]:
second_largest_value = largest_value_in_col.max()
print(f"the second larges value in the array is: {second_largest_value}")

the second larges value in the array is: 0.960204672115667


## Question 10

Write a NumPy program to create a 4x4 array with random values and find the sum of each row.

In [ ]:
arr = np.random.random(size=(4,4))
arr

array([[0.52233218, 0.54343802, 0.29830098, 0.4874728 ],
       [0.49688915, 0.96886113, 0.34606248, 0.39191382],
       [0.65569074, 0.65397833, 0.577805  , 0.2357034 ],
       [0.09400521, 0.64504178, 0.11740159, 0.85726675]])

In [ ]:
sum_of_rows = arr.sum(axis=1)

print(f"the sumof each row is: {sum_of_rows}")


the sumof each row is: [1.85154398 2.20372658 2.12317748 1.71371533]
